Extra features setup json
openvstorage/automation-lib pull request #73
Opened 2018-02-02 14:47 UTC by jeroenmaelbrancke

- mds_safety
- volumedriver config

2018-02-02 14:56 UTC, JeffreyDevloo requested changes

2018-02-02 14:56 UTC, JeffreyDevloo commented on helpers/storagedriver.py
> +    from ovs.extensions.services.service import ServiceManager
The current master branch points towards FWK 2.11
No need to have this try-except stuff

2018-02-02 14:56 UTC, JeffreyDevloo commented on setup/vpool.py
> +        if vpool_details.get('storagedriver').get('volume_manager') is not None:
If storagedriver would be filled in, I'd opt to validate the possible options (see how we validate the call params)
So something like: 
storagedriver_config = vpool_details.get('storagedriver')
if storagedriver_config (not None or empty dict) -> validate this item before proceeding

2018-02-02 15:16 UTC, jeroenmaelbrancke commented
@JeffreyDevloo can review my changes?

2018-02-06 12:20 UTC, JeffreyDevloo approved these changes

2018-02-06 12:20 UTC, merged